#!/usr/bin/python
# -*- coding: utf-8 -*-
"""MCTS Values"""
N_MCTS_ITERATION = 300
LIMIT_OF_MOVES_PER_GAME = 100

"""Reinforcment Learning values"""
NUMBER_OF_GAMES_PER_ITERATION = 1
NUMBER_OF_ITERATION_IN_TRAINING = 1
NUMBER_OF_EPOCHS_PER_GAME = 10
MODEL_NAME = 'basic_model'

TOTAL_NUMBER_OF_LAYERS = 75


NUMBER_OF_CONSIDERED_POSITIONS = 5
NUMBER_OF_POSSIBLE_MOVES = 4672
INPUT_SHAPE = (75, 8, 8)
POLICY_SHAPE = (NUMBER_OF_CONSIDERED_POSITIONS, 1)

POLICY_SHAPE_3D = (73, 8, 8)

